#!/usr/bin/env ruby
#encoding: utf-8

require 'rubyhelper'
require_relative 'libIpTek'

$verbose = ARGV.include?('-v')
$debug = ARGV.include?('-d')

if __FILE__ == $0
  password = ENV['PASSWD'] || get_password
  begin
    s = ScrapIpTek.new(password)
  rescue => e
    puts e.message.to_s.red
    exit 1
  end
  ARGV.each do |name|
    next if name[0] == '-'
    s.name = name
    print s.name.static(18), "=> ", s.ips.join(' --- '), "\n"
  end
end
